ignite:
  partition:
    count: 32
  cache:
    my_cache:
      preload: -1
      rebuild: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false