version: '2.1'

services:
  zookeeper:
    image: garland/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  master:
    image: garland/mesosphere-docker-mesos-master
    depends_on:
      - zookeeper
    environment:
      - MESOS_ZK=zk://zookeeper:2181/mesos
      - MESOS_PORT=5050
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=in_memory
      - MESOS_WORK_DIR=/var/lib/mesos
    ports:
      - "5050:5050"

  marathon:
    image: garland/mesosphere-docker-marathon
    depends_on:
      - zookeeper
      - master
    ports:
      - "8080:8080"
    command: --master zk://zookeeper:2181/mesos --zk zk://zookeeper:2181/marathon

  slave:
    image: garland/mesosphere-docker-mesos-master:latest
    depends_on:
      - zookeeper
      - marathon
    entrypoint:
      - mesos-slave
    environment:
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_LOGGING_LEVEL=INFO
