version: '2.1'

services:
  exhibitor:
    image: netflixoss/exhibitor:1.5.2
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  master:
    image: mesosphere/mesos-master:1.4.0
    depends_on:
      - exhibitor
    environment:
      - MESOS_ZK=zk://exhibitor:2181/mesos
      - MESOS_PORT=5050
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=in_memory
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_LOGGING_LEVEL=INFO
    ports:
      - "5050:5050"

  marathon:
    image: mesosphere/marathon:v1.4.9
    restart: on-failure
    depends_on:
      - master
    ports:
      - "8080:8080"
    command: --master zk://exhibitor:2181/mesos --zk zk://exhibitor:2181/marathon

  slave:
    image: mesosphere/mesos-slave:1.4.0
    depends_on:
      - marathon
    entrypoint:
      - mesos-slave
    privileged: true
    volumes:
      - "/usr/local/bin/docker:/usr/local/bin/docker:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - MESOS_MASTER=zk://exhibitor:2181/mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_LOGGING_LEVEL=INFO
      - MESOS_SYSTEMD_ENABLE_SUPPORT=false
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_ISOLATION=posix/cpu,posix/mem
